#localhost:8081
server:
  port: 8081

#DBについての情報はDataSourceConfig.javaにて設定を行う
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kyh.system.entity  # 타입 별칭이 정의된 패키지 *체크 com.winter.model com.kyh.system.entity

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: testuser
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
 