#localhost:8081
server:
  port: 8081

#DBについての情報はDataSourceConfig.javaにて設定を行う
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kyh.system.entity #체크 필요

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: testuser
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver